'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:2.0.50727.3649
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class AddQCFileDetail

    '''<summary>
    '''form1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Image4 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Image4 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LinkFile 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LinkFile As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkPrint 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LinkPrint As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkEmail 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LinkEmail As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''CtlWFActionList1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CtlWFActionList1 As Global.eWorkFlow.eFlowDoc.CtlWFActionList

    '''<summary>
    '''LBtitle 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LBtitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ChbSethuiqian 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents ChbSethuiqian As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''sqz 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents sqz As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LbFileChangeNO 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbFileChangeNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Repeater1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Repeater1 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''LbEffectDate 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbEffectDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label4 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DPLApplyDepth 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents DPLApplyDepth As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LbApplyDept 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbApplyDept As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HidApplyDeptText 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HidApplyDeptText As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HidApplyDeptValue 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HidApplyDeptValue As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TxtApplyUser 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents TxtApplyUser As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LbApplyuser 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbApplyuser As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HidApplyUser 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HidApplyUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TxtApplyDate 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents TxtApplyDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LbApplyDate 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbApplyDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtFileVersion 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents TxtFileVersion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LbFileVersion 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbFileVersion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtToTalPage 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents TxtToTalPage As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LbTotalPage 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbTotalPage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtFileName 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents TxtFileName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HIDFilename 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HIDFilename As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''LbFileName 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbFileName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DPLFileLayer 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents DPLFileLayer As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HidFileLayer 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HidFileLayer As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''LbFileLayer 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbFileLayer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Lbfilecate 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Lbfilecate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DPLFileCategory 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents DPLFileCategory As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HidFileCategoryText 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HidFileCategoryText As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HidFileCategoryValue 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HidFileCategoryValue As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''LbFileCategory 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbFileCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LbIso 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbIso As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DPLiso 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents DPLiso As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HidISO 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HidISO As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''LbIsovalue 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbIsovalue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBFileNo 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LBFileNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LbFileNOvalue 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbFileNOvalue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HidFileBH 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HidFileBH As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TxtChangeReason 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents TxtChangeReason As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LbChangeReason 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbChangeReason As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtChangePreDes 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents TxtChangePreDes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LbChangePreDes 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbChangePreDes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtChangeBehDes 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents TxtChangeBehDes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LbChangeBehDes 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbChangeBehDes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DPLLabTechniqueCharge 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents DPLLabTechniqueCharge As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HidLabTechniqueCharge 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HidLabTechniqueCharge As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''LbLabTechniqueCharge 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbLabTechniqueCharge As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CHBPaper 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CHBPaper As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''shumianjilu 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents shumianjilu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UcFileDetail4 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents UcFileDetail4 As Global.CMCFileManage.UcFileDetail

    '''<summary>
    '''CKBMeeting 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CKBMeeting As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''huiyijilu 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents huiyijilu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UcFileDetail5 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents UcFileDetail5 As Global.CMCFileManage.UcFileDetail

    '''<summary>
    '''CHBNone 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CHBNone As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LBFF1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LBFF1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBZD1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LBZD1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBFF2 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LBFF2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBZD2 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LBZD2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Hidfenfadanwei 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Hidfenfadanwei As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Repeater2 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Repeater2 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''RdBIsTeach 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents RdBIsTeach As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''HidIsteach 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HidIsteach As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TxtTeachDept 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents TxtTeachDept As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LbPaperNum 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbPaperNum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LbPaperNumValue 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LbPaperNumValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UcFileDetail1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents UcFileDetail1 As Global.CMCFileManage.UcFileDetail

    '''<summary>
    '''pb1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents pb1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label3 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ImgCenterTechniqueCharge 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents ImgCenterTechniqueCharge As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ImgCenterQuantityCharge 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents ImgCenterQuantityCharge As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ImgHighManager 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents ImgHighManager As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''UcFileDetail3 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents UcFileDetail3 As Global.CMCFileManage.UcFileDetail

    '''<summary>
    '''UcFileDetail2 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents UcFileDetail2 As Global.CMCFileManage.UcFileDetail

    '''<summary>
    '''lbQualityFinishUser 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents lbQualityFinishUser As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hs 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents hs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Hidhuishoudanwei 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Hidhuishoudanwei As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Repeater3 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Repeater3 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''GridView1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ctlWFHistory1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents ctlWFHistory1 As Global.eWorkFlow.eFlowDoc.ctlWFHistory

    '''<summary>
    '''Hiddenischange 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Hiddenischange As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HidIsNewDoc 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HidIsNewDoc As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Image1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Image2 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Image2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Image3 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Image3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HidRecordType 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HidRecordType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HidisConfirm 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HidisConfirm As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HidApplyPKID 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HidApplyPKID As Global.System.Web.UI.WebControls.HiddenField
End Class
