'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:2.0.50727.3603
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WCFService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WCFService.IWorkflowService")>  _
    Public Interface IWorkflowService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/startRuntime", ReplyAction:="http://tempuri.org/IWorkflowService/startRuntimeResponse")>  _
        Function startRuntime() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/stopRuntime", ReplyAction:="http://tempuri.org/IWorkflowService/stopRuntimeResponse")>  _
        Function stopRuntime() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/CreateWorkFlow", ReplyAction:="http://tempuri.org/IWorkflowService/CreateWorkFlowResponse"),  _
         System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WFUserInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WFUserInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.Enm_AuthorizeSet_AuthorizeType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.TemplateStateInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateTransactInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.BusinessParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.ChildWorkFlowParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkFlowInstanceInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkFlowInstanceInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateNextPersonInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateNextPersonInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.StateInstanceInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.StateInstanceInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateTransactInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of String, String))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Guid()))>  _
        Function CreateWorkFlow(ByVal parameter As Platform.eWorkFlow.Model.WorkflowStartParameter) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/BusinessSubmit", ReplyAction:="http://tempuri.org/IWorkflowService/BusinessSubmitResponse"),  _
         System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkflowStartParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WFUserInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WFUserInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.Enm_AuthorizeSet_AuthorizeType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.TemplateStateInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateTransactInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.BusinessParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.ChildWorkFlowParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkFlowInstanceInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkFlowInstanceInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateNextPersonInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateNextPersonInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.StateInstanceInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.StateInstanceInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateTransactInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of String, String))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Guid()))>  _
        Function BusinessSubmit(ByVal SubmitResult As Platform.eWorkFlow.Model.SubmitResult, ByVal IsNewInstance As Boolean) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/gotoState", ReplyAction:="http://tempuri.org/IWorkflowService/gotoStateResponse"),  _
         System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkflowStartParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WFUserInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WFUserInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.Enm_AuthorizeSet_AuthorizeType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.TemplateStateInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateTransactInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.BusinessParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.ChildWorkFlowParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkFlowInstanceInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkFlowInstanceInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateNextPersonInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateNextPersonInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.StateInstanceInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.StateInstanceInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateTransactInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of String, String))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Guid()))>  _
        Function gotoState(ByVal submitResult As Platform.eWorkFlow.Model.SubmitResult) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/addLogicState", ReplyAction:="http://tempuri.org/IWorkflowService/addLogicStateResponse"),  _
         System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkflowStartParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WFUserInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WFUserInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.Enm_AuthorizeSet_AuthorizeType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.TemplateStateInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateTransactInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.BusinessParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.ChildWorkFlowParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkFlowInstanceInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkFlowInstanceInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateNextPersonInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateNextPersonInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.StateInstanceInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.StateInstanceInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateTransactInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of String, String))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Guid()))>  _
        Function addLogicState(ByVal submitResult As Platform.eWorkFlow.Model.SubmitResult, ByVal IsNewInstance As Boolean) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/SetStateNextPerson", ReplyAction:="http://tempuri.org/IWorkflowService/SetStateNextPersonResponse"),  _
         System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkflowStartParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WFUserInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WFUserInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.Enm_AuthorizeSet_AuthorizeType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.TemplateStateInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateTransactInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.BusinessParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.ChildWorkFlowParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkFlowInstanceInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkFlowInstanceInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateNextPersonInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateNextPersonInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.StateInstanceInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.StateInstanceInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateTransactInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of String, String))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Guid()))>  _
        Function SetStateNextPerson(ByVal submitResult As Platform.eWorkFlow.Model.SubmitResult) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/ProcessFreeze", ReplyAction:="http://tempuri.org/IWorkflowService/ProcessFreezeResponse"),  _
         System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkflowStartParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WFUserInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WFUserInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.Enm_AuthorizeSet_AuthorizeType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.TemplateStateInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateTransactInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.BusinessParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.ChildWorkFlowParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkFlowInstanceInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkFlowInstanceInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateNextPersonInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateNextPersonInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.StateInstanceInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.StateInstanceInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateTransactInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of String, String))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Guid()))>  _
        Function ProcessFreeze(ByVal submitResult As Platform.eWorkFlow.Model.SubmitResult, ByVal InstanceStatus As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/RevokeState", ReplyAction:="http://tempuri.org/IWorkflowService/RevokeStateResponse"),  _
         System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkflowStartParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WFUserInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WFUserInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.Enm_AuthorizeSet_AuthorizeType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.TemplateStateInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateTransactInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.BusinessParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.ChildWorkFlowParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkFlowInstanceInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkFlowInstanceInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateNextPersonInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateNextPersonInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.StateInstanceInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.StateInstanceInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateTransactInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of String, String))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Guid()))>  _
        Function RevokeState(ByVal SubmitInfo As Platform.eWorkFlow.Model.SubmitResult) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/SaveTransactInfo", ReplyAction:="http://tempuri.org/IWorkflowService/SaveTransactInfoResponse"),  _
         System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkflowStartParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WFUserInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WFUserInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.Enm_AuthorizeSet_AuthorizeType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.TemplateStateInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateTransactInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.BusinessParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.ChildWorkFlowParameter)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkFlowInstanceInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.WorkFlowInstanceInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateNextPersonInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateNextPersonInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.StateInstanceInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.StateInstanceInfo)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Platform.eWorkFlow.Model.InstanceStateTransactInfo())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of String, String))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Guid()))>  _
        Function SaveTransactInfo(ByVal SubmitInfo As Platform.eWorkFlow.Model.SubmitResult) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/GetInstanceInfoByInstanceKeyID", ReplyAction:="http://tempuri.org/IWorkflowService/GetInstanceInfoByInstanceKeyIDResponse")>  _
        Function GetInstanceInfoByInstanceKeyID(ByVal InstanceKeyID As Integer) As Platform.eWorkFlow.Model.WorkFlowInstanceInfo
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/GetInstanceInfoByInstanceID", ReplyAction:="http://tempuri.org/IWorkflowService/GetInstanceInfoByInstanceIDResponse")>  _
        Function GetInstanceInfoByInstanceID(ByVal InstanceID As System.Guid) As Platform.eWorkFlow.Model.WorkFlowInstanceInfo
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/GetAllBatchAduitWorkFlowInstance", ReplyAction:="http://tempuri.org/IWorkflowService/GetAllBatchAduitWorkFlowInstanceResponse")>  _
        Function GetAllBatchAduitWorkFlowInstance() As Platform.eWorkFlow.Model.WorkFlowInstanceInfo()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/GetStateNextPerson", ReplyAction:="http://tempuri.org/IWorkflowService/GetStateNextPersonResponse")>  _
        Function GetStateNextPerson(ByVal InstanceID As System.Guid, ByVal StateName As String, ByVal InstanceKeyID As Integer) As Platform.eWorkFlow.Model.InstanceStateNextPersonInfo()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/GetInstanceStateInfo", ReplyAction:="http://tempuri.org/IWorkflowService/GetInstanceStateInfoResponse")>  _
        Function GetInstanceStateInfo(ByVal InstanceID As System.Guid, ByVal InstanceKeyID As Integer) As Platform.eWorkFlow.Model.StateInstanceInfo()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/GetStateInstanceTransact", ReplyAction:="http://tempuri.org/IWorkflowService/GetStateInstanceTransactResponse")>  _
        Function GetStateInstanceTransact(ByVal StateInstanceKeyID As Integer) As Platform.eWorkFlow.Model.InstanceStateTransactInfo()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/DeleteInstanceInfoByInstanceID", ReplyAction:="http://tempuri.org/IWorkflowService/DeleteInstanceInfoByInstanceIDResponse")>  _
        Sub DeleteInstanceInfoByInstanceID(ByVal InstanceID As System.Guid)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/DeleteInstanceInfoByInstanceKeyID", ReplyAction:="http://tempuri.org/IWorkflowService/DeleteInstanceInfoByInstanceKeyIDResponse")>  _
        Sub DeleteInstanceInfoByInstanceKeyID(ByVal InstanceKeyID As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/DeleteNextPerson", ReplyAction:="http://tempuri.org/IWorkflowService/DeleteNextPersonResponse")>  _
        Sub DeleteNextPerson(ByVal NextPersonPKID As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/GetServerTime", ReplyAction:="http://tempuri.org/IWorkflowService/GetServerTimeResponse")>  _
        Function GetServerTime() As Date
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/GetServerVersion", ReplyAction:="http://tempuri.org/IWorkflowService/GetServerVersionResponse")>  _
        Function GetServerVersion() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/GetOverTimeInstance", ReplyAction:="http://tempuri.org/IWorkflowService/GetOverTimeInstanceResponse")>  _
        Function GetOverTimeInstance(ByVal WFLink As Boolean) As Platform.eWorkFlow.Model.WorkFlowInstanceInfo()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/GetAllWFInstance", ReplyAction:="http://tempuri.org/IWorkflowService/GetAllWFInstanceResponse")>  _
        Function GetAllWFInstance(ByVal WFLink As Boolean) As Platform.eWorkFlow.Model.WorkFlowInstanceInfo()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/clearStateInfo", ReplyAction:="http://tempuri.org/IWorkflowService/clearStateInfoResponse")>  _
        Function clearStateInfo() As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/getWorkflowInstanceFromRuntime", ReplyAction:="http://tempuri.org/IWorkflowService/getWorkflowInstanceFromRuntimeResponse")>  _
        Function getWorkflowInstanceFromRuntime() As System.Guid()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWorkflowService/GetWFInstanceTransactHistory", ReplyAction:="http://tempuri.org/IWorkflowService/GetWFInstanceTransactHistoryResponse")>  _
        Function GetWFInstanceTransactHistory(ByVal InstanceID As System.Guid, ByVal TemplateID As Integer) As System.Data.DataSet
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IWorkflowServiceChannel
        Inherits WCFService.IWorkflowService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class WorkflowServiceClient
        Inherits System.ServiceModel.ClientBase(Of WCFService.IWorkflowService)
        Implements WCFService.IWorkflowService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function startRuntime() As Integer Implements WCFService.IWorkflowService.startRuntime
            Return MyBase.Channel.startRuntime
        End Function
        
        Public Function stopRuntime() As Integer Implements WCFService.IWorkflowService.stopRuntime
            Return MyBase.Channel.stopRuntime
        End Function
        
        Public Function CreateWorkFlow(ByVal parameter As Platform.eWorkFlow.Model.WorkflowStartParameter) As Integer Implements WCFService.IWorkflowService.CreateWorkFlow
            Return MyBase.Channel.CreateWorkFlow(parameter)
        End Function
        
        Public Function BusinessSubmit(ByVal SubmitResult As Platform.eWorkFlow.Model.SubmitResult, ByVal IsNewInstance As Boolean) As Boolean Implements WCFService.IWorkflowService.BusinessSubmit
            Return MyBase.Channel.BusinessSubmit(SubmitResult, IsNewInstance)
        End Function
        
        Public Function gotoState(ByVal submitResult As Platform.eWorkFlow.Model.SubmitResult) As Boolean Implements WCFService.IWorkflowService.gotoState
            Return MyBase.Channel.gotoState(submitResult)
        End Function
        
        Public Function addLogicState(ByVal submitResult As Platform.eWorkFlow.Model.SubmitResult, ByVal IsNewInstance As Boolean) As Integer Implements WCFService.IWorkflowService.addLogicState
            Return MyBase.Channel.addLogicState(submitResult, IsNewInstance)
        End Function
        
        Public Function SetStateNextPerson(ByVal submitResult As Platform.eWorkFlow.Model.SubmitResult) As Boolean Implements WCFService.IWorkflowService.SetStateNextPerson
            Return MyBase.Channel.SetStateNextPerson(submitResult)
        End Function
        
        Public Function ProcessFreeze(ByVal submitResult As Platform.eWorkFlow.Model.SubmitResult, ByVal InstanceStatus As Integer) As Boolean Implements WCFService.IWorkflowService.ProcessFreeze
            Return MyBase.Channel.ProcessFreeze(submitResult, InstanceStatus)
        End Function
        
        Public Function RevokeState(ByVal SubmitInfo As Platform.eWorkFlow.Model.SubmitResult) As Boolean Implements WCFService.IWorkflowService.RevokeState
            Return MyBase.Channel.RevokeState(SubmitInfo)
        End Function
        
        Public Function SaveTransactInfo(ByVal SubmitInfo As Platform.eWorkFlow.Model.SubmitResult) As Boolean Implements WCFService.IWorkflowService.SaveTransactInfo
            Return MyBase.Channel.SaveTransactInfo(SubmitInfo)
        End Function
        
        Public Function GetInstanceInfoByInstanceKeyID(ByVal InstanceKeyID As Integer) As Platform.eWorkFlow.Model.WorkFlowInstanceInfo Implements WCFService.IWorkflowService.GetInstanceInfoByInstanceKeyID
            Return MyBase.Channel.GetInstanceInfoByInstanceKeyID(InstanceKeyID)
        End Function
        
        Public Function GetInstanceInfoByInstanceID(ByVal InstanceID As System.Guid) As Platform.eWorkFlow.Model.WorkFlowInstanceInfo Implements WCFService.IWorkflowService.GetInstanceInfoByInstanceID
            Return MyBase.Channel.GetInstanceInfoByInstanceID(InstanceID)
        End Function
        
        Public Function GetAllBatchAduitWorkFlowInstance() As Platform.eWorkFlow.Model.WorkFlowInstanceInfo() Implements WCFService.IWorkflowService.GetAllBatchAduitWorkFlowInstance
            Return MyBase.Channel.GetAllBatchAduitWorkFlowInstance
        End Function
        
        Public Function GetStateNextPerson(ByVal InstanceID As System.Guid, ByVal StateName As String, ByVal InstanceKeyID As Integer) As Platform.eWorkFlow.Model.InstanceStateNextPersonInfo() Implements WCFService.IWorkflowService.GetStateNextPerson
            Return MyBase.Channel.GetStateNextPerson(InstanceID, StateName, InstanceKeyID)
        End Function
        
        Public Function GetInstanceStateInfo(ByVal InstanceID As System.Guid, ByVal InstanceKeyID As Integer) As Platform.eWorkFlow.Model.StateInstanceInfo() Implements WCFService.IWorkflowService.GetInstanceStateInfo
            Return MyBase.Channel.GetInstanceStateInfo(InstanceID, InstanceKeyID)
        End Function
        
        Public Function GetStateInstanceTransact(ByVal StateInstanceKeyID As Integer) As Platform.eWorkFlow.Model.InstanceStateTransactInfo() Implements WCFService.IWorkflowService.GetStateInstanceTransact
            Return MyBase.Channel.GetStateInstanceTransact(StateInstanceKeyID)
        End Function
        
        Public Sub DeleteInstanceInfoByInstanceID(ByVal InstanceID As System.Guid) Implements WCFService.IWorkflowService.DeleteInstanceInfoByInstanceID
            MyBase.Channel.DeleteInstanceInfoByInstanceID(InstanceID)
        End Sub
        
        Public Sub DeleteInstanceInfoByInstanceKeyID(ByVal InstanceKeyID As Integer) Implements WCFService.IWorkflowService.DeleteInstanceInfoByInstanceKeyID
            MyBase.Channel.DeleteInstanceInfoByInstanceKeyID(InstanceKeyID)
        End Sub
        
        Public Sub DeleteNextPerson(ByVal NextPersonPKID As Integer) Implements WCFService.IWorkflowService.DeleteNextPerson
            MyBase.Channel.DeleteNextPerson(NextPersonPKID)
        End Sub
        
        Public Function GetServerTime() As Date Implements WCFService.IWorkflowService.GetServerTime
            Return MyBase.Channel.GetServerTime
        End Function
        
        Public Function GetServerVersion() As String Implements WCFService.IWorkflowService.GetServerVersion
            Return MyBase.Channel.GetServerVersion
        End Function
        
        Public Function GetOverTimeInstance(ByVal WFLink As Boolean) As Platform.eWorkFlow.Model.WorkFlowInstanceInfo() Implements WCFService.IWorkflowService.GetOverTimeInstance
            Return MyBase.Channel.GetOverTimeInstance(WFLink)
        End Function
        
        Public Function GetAllWFInstance(ByVal WFLink As Boolean) As Platform.eWorkFlow.Model.WorkFlowInstanceInfo() Implements WCFService.IWorkflowService.GetAllWFInstance
            Return MyBase.Channel.GetAllWFInstance(WFLink)
        End Function
        
        Public Function clearStateInfo() As Boolean Implements WCFService.IWorkflowService.clearStateInfo
            Return MyBase.Channel.clearStateInfo
        End Function
        
        Public Function getWorkflowInstanceFromRuntime() As System.Guid() Implements WCFService.IWorkflowService.getWorkflowInstanceFromRuntime
            Return MyBase.Channel.getWorkflowInstanceFromRuntime
        End Function
        
        Public Function GetWFInstanceTransactHistory(ByVal InstanceID As System.Guid, ByVal TemplateID As Integer) As System.Data.DataSet Implements WCFService.IWorkflowService.GetWFInstanceTransactHistory
            Return MyBase.Channel.GetWFInstanceTransactHistory(InstanceID, TemplateID)
        End Function
    End Class
End Namespace
