'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:2.0.50727.3082
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class _Default

    '''<summary>
    '''Head1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''username 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents username As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''LKBlogoOUT 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents LKBlogoOUT As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''yewu1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents yewu1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''inquote 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents inquote As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''zhuguanwork 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents zhuguanwork As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li3 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Li3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''reportsh 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents reportsh As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li2 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Li2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Li1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''yichang 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents yichang As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li4 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Li4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li5 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Li5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Customerwork1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Customerwork1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Customerwork2 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Customerwork2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CustomerWork 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CustomerWork As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''yewu3 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents yewu3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''yewu2 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents yewu2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''work4 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents work4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''work1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents work1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''worke2 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents worke2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Allreport 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Allreport As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''work3 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents work3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''jinguan 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents jinguan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Tongji 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Tongji As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''duizhang 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents duizhang As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''leadreport 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents leadreport As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''store 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents store As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''manage 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents manage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''itemmanage 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents itemmanage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sysuse 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents sysuse As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gonggao 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents gonggao As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''usercenter 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents usercenter As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cus 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents cus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''yewu4 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents yewu4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li6 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Li6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li7 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Li7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divSell 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents divSell As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DIVComplaints 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents DIVComplaints As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HidInitUrl 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HidInitUrl As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HidInitTitle 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HidInitTitle As Global.System.Web.UI.WebControls.HiddenField
End Class
