'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:2.0.50727.3082
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 之類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建 Visual Studio 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強型別資源類別
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.Resource", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強型別資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查詢類似 确定 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property BtnAduitTitle() As String
            Get
                Return ResourceManager.GetString("BtnAduitTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 當設定優先級為高時立即發送郵件通知下一站人員 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property ChkProrityTop() As String
            Get
                Return ResourceManager.GetString("ChkProrityTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 選擇 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property ChkTtile() As String
            Get
                Return ResourceManager.GetString("ChkTtile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 文件刪除時發生錯誤！請聯繫系統管理員或系統開發人員。錯誤信息為: 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property DeleteErrorAlert() As String
            Get
                Return ResourceManager.GetString("DeleteErrorAlert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 請確認是否移除本份文件? 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property DeleteFileConfirm() As String
            Get
                Return ResourceManager.GetString("DeleteFileConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 時發生錯誤！請聯繫系統管理員或系統開發人員。錯誤信息為: 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property ErrorAlert() As String
            Get
                Return ResourceManager.GetString("ErrorAlert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 文件 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property ErrorFile() As String
            Get
                Return ResourceManager.GetString("ErrorFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 服務器處理過程中出現異常! 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property ErrorTitle() As String
            Get
                Return ResourceManager.GetString("ErrorTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 文件可能已經被其他辦理人員處理！ 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property FileBanliAlert() As String
            Get
                Return ResourceManager.GetString("FileBanliAlert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 流程未啟用(不能進行流程審核),请检查流程配置并启动流程! 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property FlowActiveError() As String
            Get
                Return ResourceManager.GetString("FlowActiveError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 請填寫處理意見 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property FlowAdviceTitle() As String
            Get
                Return ResourceManager.GetString("FlowAdviceTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 狀態 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property FlowStateTitle() As String
            Get
                Return ResourceManager.GetString("FlowStateTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 當前文件尚未實作IDocInfo接口,無法執行文件保存功能! 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property IDocInfoerror() As String
            Get
                Return ResourceManager.GetString("IDocInfoerror", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 處理意见 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property LblAdviceTitle() As String
            Get
                Return ResourceManager.GetString("LblAdviceTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 優先級 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property lblProprityTitle() As String
            Get
                Return ResourceManager.GetString("lblProprityTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 直接主管： 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property LeaderManageTitle() As String
            Get
                Return ResourceManager.GetString("LeaderManageTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 取消 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property linkCancelTitle() As String
            Get
                Return ResourceManager.GetString("linkCancelTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 刪除 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property LinkDeleteTitle() As String
            Get
                Return ResourceManager.GetString("LinkDeleteTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 离开 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property LinkLeaveTitle() As String
            Get
                Return ResourceManager.GetString("LinkLeaveTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 管理 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property LinkManageTitle() As String
            Get
                Return ResourceManager.GetString("LinkManageTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 保存 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property LinkSaveTitle() As String
            Get
                Return ResourceManager.GetString("LinkSaveTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 正在獲取數據,請稍候.... 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property LoadMag() As String
            Get
                Return ResourceManager.GetString("LoadMag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 會簽 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property MutliSignBZ() As String
            Get
                Return ResourceManager.GetString("MutliSignBZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 流程下步辦理人員設置有誤! 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property NextUserError() As String
            Get
                Return ResourceManager.GetString("NextUserError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 搜索不到與當前文件其對應的流程定義文件! 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property NOFlowInfo() As String
            Get
                Return ResourceManager.GetString("NOFlowInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 必須設定流程名稱和流程版本! 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property NOFlowParam() As String
            Get
                Return ResourceManager.GetString("NOFlowParam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 依設定搜索不到駁回人員! 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property NOFlowRejectUser() As String
            Get
                Return ResourceManager.GetString("NOFlowRejectUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 一般 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Prority1() As String
            Get
                Return ResourceManager.GetString("Prority1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 緊急 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Prority2() As String
            Get
                Return ResourceManager.GetString("Prority2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 辦理時間 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property RecordCTTitle() As String
            Get
                Return ResourceManager.GetString("RecordCTTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 文件儲存時發生錯誤！請聯繫系統管理員或系統開發人員。錯誤信息為: 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property SaveErrorAlert() As String
            Get
                Return ResourceManager.GetString("SaveErrorAlert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 依設定搜索不到下步流程人員! 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property SearchNextUser() As String
            Get
                Return ResourceManager.GetString("SearchNextUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 請選擇人員信息 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property SelectUserTitle() As String
            Get
                Return ResourceManager.GetString("SelectUserTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 特定部門： 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property SepcialDeptTitle() As String
            Get
                Return ResourceManager.GetString("SepcialDeptTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 特定群組 : 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property SepcialGroupTitle() As String
            Get
                Return ResourceManager.GetString("SepcialGroupTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 特定欄位： 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property SepcialLanWei() As String
            Get
                Return ResourceManager.GetString("SepcialLanWei", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 特定角色： 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property SepcialRoleTitle() As String
            Get
                Return ResourceManager.GetString("SepcialRoleTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 特定步鄹： 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property SepcialStatus() As String
            Get
                Return ResourceManager.GetString("SepcialStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 特定人員： 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property SepcialUserTitle() As String
            Get
                Return ResourceManager.GetString("SepcialUserTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 簽核人員 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property SignUserTitle() As String
            Get
                Return ResourceManager.GetString("SignUserTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 狀態名稱 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property StateNameTitle() As String
            Get
                Return ResourceManager.GetString("StateNameTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 執行動作 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property TranOptionTitle() As String
            Get
                Return ResourceManager.GetString("TranOptionTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 簽核意見 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property TransactResult() As String
            Get
                Return ResourceManager.GetString("TransactResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 姓名 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property UserNameTitle() As String
            Get
                Return ResourceManager.GetString("UserNameTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 帳號 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property UserSIDTitle() As String
            Get
                Return ResourceManager.GetString("UserSIDTitle", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
